apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.prod.yml -o k8s/
    kompose.version: 1.38.0 (HEAD)
  labels:
    io.kompose.service: watchtower
  name: watchtower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: watchtower
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f compose.prod.yml -o k8s/
        kompose.version: 1.38.0 (HEAD)
      labels:
        io.kompose.service: watchtower
    spec:
      containers:
        - env:
            - name: WATCHTOWER_CLEANUP
              value: "true"
            - name: WATCHTOWER_LABEL_ENABLE
              value: "true"
            - name: WATCHTOWER_POLL_INTERVAL
              value: "300"
          image: containrrr/watchtower:1.7.1
          name: moca-watchtower
      restartPolicy: Always
